class DiseaseInfo {
  final String cropEn;
  final String cropAr;
  final String diseaseEn;
  final String diseaseAr;
  final bool isHealthy;
  final bool isNotPlant;
  final String pathogenEn;
  final String pathogenAr;
  final String symptomsEn;
  final String symptomsAr;
  final String causesEn;
  final String causesAr;
  final String chemicalTreatmentEn;
  final String chemicalTreatmentAr;
  final String organicTreatmentEn;
  final String organicTreatmentAr;
  final String preventionEn;
  final String preventionAr;
  final String severity;
  final String seasonEn;
  final String seasonAr;
  final String sourceUrl;

  const DiseaseInfo({
    required this.cropEn,
    required this.cropAr,
    required this.diseaseEn,
    required this.diseaseAr,
    required this.isHealthy,
    this.isNotPlant = false,
    required this.pathogenEn,
    required this.pathogenAr,
    required this.symptomsEn,
    required this.symptomsAr,
    required this.causesEn,
    required this.causesAr,
    required this.chemicalTreatmentEn,
    required this.chemicalTreatmentAr,
    required this.organicTreatmentEn,
    required this.organicTreatmentAr,
    required this.preventionEn,
    required this.preventionAr,
    required this.severity,
    required this.seasonEn,
    required this.seasonAr,
    required this.sourceUrl,
  });

  String crop(String lang) => lang == 'ar' ? cropAr : cropEn;
  String disease(String lang) => lang == 'ar' ? diseaseAr : diseaseEn;
  String pathogen(String lang) => lang == 'ar' ? pathogenAr : pathogenEn;
  String symptoms(String lang) => lang == 'ar' ? symptomsAr : symptomsEn;
  String causes(String lang) => lang == 'ar' ? causesAr : causesEn;
  String chemicalTreatment(String lang) => lang == 'ar' ? chemicalTreatmentAr : chemicalTreatmentEn;
  String organicTreatment(String lang) => lang == 'ar' ? organicTreatmentAr : organicTreatmentEn;
  String prevention(String lang) => lang == 'ar' ? preventionAr : preventionEn;
  String season(String lang) => lang == 'ar' ? seasonAr : seasonEn;
}

const _hSymptomsEn = 'Uniform green leaves, firm stems, no spots, lesions, mold, or curling.';
const _hSymptomsAr = 'أوراق خضراء موحدة، سيقان قوية، بدون بقع أو تقرحات أو عفن أو التفاف.';
const _hCausesEn = 'Adequate sunlight, balanced irrigation, good air circulation, moderate humidity.';
const _hCausesAr = 'ضوء شمس كافٍ، ري متوازن، تهوية جيدة، رطوبة معتدلة.';
const _hChemEn = 'Not required.';
const _hChemAr = 'غير مطلوب.';
const _hOrgEn = 'Preventive only: compost, mulching, foliar seaweed extract if needed.';
const _hOrgAr = 'وقائي فقط: كمبوست، تغطية التربة، رش مستخلص أعشاب بحرية عند الحاجة.';
const _hPrevEn = 'Continue good agricultural practice: crop rotation, sanitation, resistant cultivars.';
const _hPrevAr = 'استمر في الممارسات الجيدة: دورة زراعية، نظافة، أصناف مقاومة.';

class DiseaseCatalog {
  /// Label returned by the model for non-plant / random images.
  static const String notPlantLabel = 'Not_plant';

  static const Map<String, DiseaseInfo> _db = {
    // ── Non-plant class ──────────────────────────────────────────────────
    // Returned when the uploaded image is not a plant leaf. No treatment,
    // causes, or recommendations — those stay empty on purpose.
    'Not_plant': DiseaseInfo(
      cropEn: '', cropAr: '',
      diseaseEn: 'Not a plant', diseaseAr: 'ليست نبتة',
      isHealthy: false, isNotPlant: true,
      pathogenEn: '', pathogenAr: '',
      symptomsEn: '', symptomsAr: '',
      causesEn: '', causesAr: '',
      chemicalTreatmentEn: '', chemicalTreatmentAr: '',
      organicTreatmentEn: '', organicTreatmentAr: '',
      preventionEn: '', preventionAr: '',
      severity: 'None', seasonEn: '', seasonAr: '',
      sourceUrl: '',
    ),
    'Apple___Apple_scab': DiseaseInfo(
      cropEn: 'Apple', cropAr: 'تفاح',
      diseaseEn: 'Apple Scab', diseaseAr: 'جرب التفاح',
      isHealthy: false,
      pathogenEn: 'Fungus: Venturia inaequalis', pathogenAr: 'فطر: Venturia inaequalis',
      symptomsEn: 'Olive-green velvety spots with fringed borders on leaves; turn brown/black, cause yellowing and drop. Fruit develops corky, cracked spots.',
      symptomsAr: 'بقع مخملية خضراء زيتونية ذات حواف مهدبة على الأوراق، تتحول للبني/الأسود وتسبب اصفرار وسقوط الورق. الثمار تصاب بتشققات فلينية.',
      causesEn: 'Cool, wet spring weather; prolonged leaf wetness; high humidity. Dense canopy, poor air circulation, infected fallen leaves left on ground.',
      causesAr: 'طقس ربيعي بارد ورطب، وبقاء الأوراق مبللة فترة طويلة، رطوبة مرتفعة. كثافة المجموع الخضري، ضعف التهوية، ترك الأوراق المصابة الساقطة على الأرض.',
      chemicalTreatmentEn: 'Captan, myclobutanil, or mancozeb applied at green-tip through petal fall; rotate FRAC groups to prevent resistance.',
      chemicalTreatmentAr: 'كابتان أو مايكلوبوتانيل أو مانكوزيب من مرحلة البرعم الأخضر حتى سقوط البتلات؛ مع تبديل مجموعات الـ FRAC لمنع المقاومة.',
      organicTreatmentEn: 'Sulfur or copper sprays at early bud stage; lime-sulfur as a dormant spray.',
      organicTreatmentAr: 'رش الكبريت أو النحاس في مرحلة البرعم المبكرة؛ رش الكبريت الجيري في فترة السكون.',
      preventionEn: 'Rake and destroy fallen leaves, prune for airflow, plant resistant cultivars (Liberty, Enterprise, Freedom).',
      preventionAr: 'جمع وإتلاف الأوراق الساقطة، التقليم لتحسين التهوية، زراعة أصناف مقاومة (Liberty, Enterprise, Freedom).',
      severity: 'High', seasonEn: 'Spring and early summer', seasonAr: 'الربيع وبداية الصيف',
      sourceUrl: 'https://extension.umn.edu/plant-diseases/apple-scab',
    ),
    'Apple___Black_rot': DiseaseInfo(
      cropEn: 'Apple', cropAr: 'تفاح',
      diseaseEn: 'Black Rot (Frogeye Leaf Spot)', diseaseAr: 'العفن الأسود (بقعة عين الضفدع)',
      isHealthy: false,
      pathogenEn: 'Fungus: Diplodia seriata', pathogenAr: 'فطر: Diplodia seriata',
      symptomsEn: 'Frogeye leaf spot: circular spots with purple edges and tan centers. Fruit shows brown rot with concentric rings at blossom end. Sunken cankers on branches.',
      symptomsAr: 'بقعة عين الضفدع: بقع دائرية بأطراف بنفسجية ومراكز بنية فاتحة. تعفن بني مع حلقات دائرية على الثمار من جهة الزهرة. تقرحات غائرة في الأفرع.',
      causesEn: 'Warm, humid summers; wounds on bark; freeze damage. Drought stress, winter injury, nutrient deficiency (especially potassium), dead wood.',
      causesAr: 'صيف دافئ رطب، جروح في اللحاء، أضرار صقيع. إجهاد جفاف، إصابة شتوية، نقص عناصر (خاصة البوتاسيوم)، خشب ميت.',
      chemicalTreatmentEn: 'Captan, thiophanate-methyl, or strobilurins (Pristine, Merivon) if sanitation fails.',
      chemicalTreatmentAr: 'كابتان أو ثيوفانات ميثيل أو ستروبيلورينات (Pristine, Merivon) عند فشل النظافة الزراعية.',
      organicTreatmentEn: 'Copper or sulfur sprays; remove mummified fruit and prune out cankers.',
      organicTreatmentAr: 'رش النحاس أو الكبريت، إزالة الثمار الجافة وتقليم التقرحات.',
      preventionEn: 'Sanitation is primary: prune dead wood, remove mummies, dispose of pruning debris; avoid tree stress.',
      preventionAr: 'النظافة أولًا: تقليم الخشب الميت، إزالة الثمار المحنطة، التخلص من مخلفات التقليم، تجنب إجهاد الأشجار.',
      severity: 'Medium', seasonEn: 'Late summer through fall', seasonAr: 'أواخر الصيف وحتى الخريف',
      sourceUrl: 'https://extension.umn.edu/plant-diseases/black-rot-apple',
    ),
    'Apple___Cedar_apple_rust': DiseaseInfo(
      cropEn: 'Apple', cropAr: 'تفاح',
      diseaseEn: 'Cedar Apple Rust', diseaseAr: 'صدأ التفاح والأرز (سيدر)',
      isHealthy: false,
      pathogenEn: 'Fungus: Gymnosporangium juniperi-virginianae', pathogenAr: 'فطر: Gymnosporangium juniperi-virginianae',
      symptomsEn: 'Bright orange-yellow spots on upper leaf surface; tube-like structures (aecia) on lower surface; deformed fruit on blossom end.',
      symptomsAr: 'بقع برتقالية-صفراء لامعة على السطح العلوي للورقة، تراكيب أنبوبية (aecia) على السطح السفلي، تشوه الثمار من جهة الزهرة.',
      causesEn: 'Wet spring; proximity to juniper/eastern red cedar trees (within 1-2 miles). Alternate host (juniper) nearby is required for disease cycle.',
      causesAr: 'ربيع ممطر، وجود أشجار الأرز أو العرعر قريبة (على بعد 1-2 ميل). وجود العائل البديل (العرعر/السيدر) ضروري لدورة المرض.',
      chemicalTreatmentEn: 'Mancozeb or myclobutanil from pink-bud stage through first cover spray.',
      chemicalTreatmentAr: 'مانكوزيب أو مايكلوبوتانيل من مرحلة البرعم الوردي وحتى أول رشة تغطية.',
      organicTreatmentEn: 'Sulfur sprays; prune galls from nearby junipers before April 1.',
      organicTreatmentAr: 'رش الكبريت، إزالة التورمات (galls) من أشجار العرعر قبل 1 أبريل.',
      preventionEn: 'Plant resistant varieties (Liberty, Freedom, William\'s Pride); remove cedar/juniper trees near orchard when possible.',
      preventionAr: 'زراعة أصناف مقاومة (Liberty, Freedom, William\'s Pride)، إزالة أشجار العرعر القريبة إن أمكن.',
      severity: 'Medium', seasonEn: 'Spring (April–June)', seasonAr: 'الربيع (أبريل-يونيو)',
      sourceUrl: 'https://extension.umn.edu/plant-diseases/cedar-apple-rust',
    ),
    'Apple___healthy': DiseaseInfo(
      cropEn: 'Apple', cropAr: 'تفاح',
      diseaseEn: 'Healthy', diseaseAr: 'سليم', isHealthy: true,
      pathogenEn: 'None', pathogenAr: 'لا يوجد',
      symptomsEn: _hSymptomsEn, symptomsAr: _hSymptomsAr,
      causesEn: _hCausesEn, causesAr: _hCausesAr,
      chemicalTreatmentEn: _hChemEn, chemicalTreatmentAr: _hChemAr,
      organicTreatmentEn: _hOrgEn, organicTreatmentAr: _hOrgAr,
      preventionEn: _hPrevEn, preventionAr: _hPrevAr,
      severity: 'None', seasonEn: 'All seasons', seasonAr: 'جميع المواسم',
      sourceUrl: 'https://www.apsnet.org/edcenter/Pages/default.aspx',
    ),
    'Blueberry___healthy': DiseaseInfo(
      cropEn: 'Blueberry', cropAr: 'توت أزرق',
      diseaseEn: 'Healthy', diseaseAr: 'سليم', isHealthy: true,
      pathogenEn: 'None', pathogenAr: 'لا يوجد',
      symptomsEn: _hSymptomsEn, symptomsAr: _hSymptomsAr,
      causesEn: _hCausesEn, causesAr: _hCausesAr,
      chemicalTreatmentEn: _hChemEn, chemicalTreatmentAr: _hChemAr,
      organicTreatmentEn: _hOrgEn, organicTreatmentAr: _hOrgAr,
      preventionEn: _hPrevEn, preventionAr: _hPrevAr,
      severity: 'None', seasonEn: 'All seasons', seasonAr: 'جميع المواسم',
      sourceUrl: 'https://www.apsnet.org/edcenter/Pages/default.aspx',
    ),
    'Cherry_(including_sour)___Powdery_mildew': DiseaseInfo(
      cropEn: 'Cherry', cropAr: 'كرز',
      diseaseEn: 'Powdery Mildew', diseaseAr: 'البياض الدقيقي',
      isHealthy: false,
      pathogenEn: 'Fungus: Podosphaera clandestina', pathogenAr: 'فطر: Podosphaera clandestina',
      symptomsEn: 'White powdery fungal growth on leaves and shoots; leaves curl upward; new shoots stunted; fruit develops white patches.',
      symptomsAr: 'نموات فطرية بيضاء دقيقية على الأوراق والأفرع، التفاف الأوراق للأعلى، تقزم الأفرع الجديدة، ظهور بقع بيضاء على الثمار.',
      causesEn: 'Warm days (20–27°C) with cool nights; dry conditions. Shaded, dense canopies; excess nitrogen fertilization; poor air circulation.',
      causesAr: 'نهار دافئ (20-27°م) وليل بارد، ظروف جافة. المجموع الخضري المتشابك المظلّل، الإفراط في التسميد الآزوتي، ضعف التهوية.',
      chemicalTreatmentEn: 'FRAC Group 3, 7, or 11 fungicides; Quintec (FRAC 13) or Vivando (FRAC 50) starting at petal fall.',
      chemicalTreatmentAr: 'مبيدات من مجموعة FRAC 3 أو 7 أو 11، Quintec (FRAC 13) أو Vivando (FRAC 50) بدءًا من سقوط البتلات.',
      organicTreatmentEn: 'Sulfur sprays, potassium bicarbonate, horticultural oils, milk solution (1:9 with water).',
      organicTreatmentAr: 'رش الكبريت، بيكربونات البوتاسيوم، الزيوت البستانية، محلول الحليب (1 : 9 مع الماء).',
      preventionEn: 'Prune for good airflow; avoid excess nitrogen; plant resistant cultivars; morning irrigation only.',
      preventionAr: 'التقليم لتهوية جيدة، تجنب الإفراط في الآزوت، زراعة أصناف مقاومة، الري صباحًا فقط.',
      severity: 'Medium', seasonEn: 'Late spring through summer', seasonAr: 'أواخر الربيع حتى الصيف',
      sourceUrl: 'https://treefruit.wsu.edu/crop-protection/disease-management/cherry-powdery-mildew/',
    ),
    'Cherry_(including_sour)___healthy': DiseaseInfo(
      cropEn: 'Cherry', cropAr: 'كرز',
      diseaseEn: 'Healthy', diseaseAr: 'سليم', isHealthy: true,
      pathogenEn: 'None', pathogenAr: 'لا يوجد',
      symptomsEn: _hSymptomsEn, symptomsAr: _hSymptomsAr,
      causesEn: _hCausesEn, causesAr: _hCausesAr,
      chemicalTreatmentEn: _hChemEn, chemicalTreatmentAr: _hChemAr,
      organicTreatmentEn: _hOrgEn, organicTreatmentAr: _hOrgAr,
      preventionEn: _hPrevEn, preventionAr: _hPrevAr,
      severity: 'None', seasonEn: 'All seasons', seasonAr: 'جميع المواسم',
      sourceUrl: 'https://www.apsnet.org/edcenter/Pages/default.aspx',
    ),
    'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot': DiseaseInfo(
      cropEn: 'Corn (Maize)', cropAr: 'ذرة',
      diseaseEn: 'Gray Leaf Spot (Cercospora)', diseaseAr: 'بقعة الأوراق الرمادية (سركوسبورا)',
      isHealthy: false,
      pathogenEn: 'Fungus: Cercospora zeae-maydis', pathogenAr: 'فطر: Cercospora zeae-maydis',
      symptomsEn: 'Small pinpoint lesions with yellow halos that elongate into narrow rectangular brown-gray lesions restricted by leaf veins.',
      symptomsAr: 'بقع صغيرة دقيقة بهالة صفراء تمتد لتصبح بقع مستطيلة رفيعة بنية-رمادية محصورة بين عروق الأوراق.',
      causesEn: 'High humidity (>90%), warm temperatures (25-30°C), prolonged leaf wetness, continuous corn cropping. No-till farming + continuous corn + dense planting.',
      causesAr: 'رطوبة عالية (>90%)، حرارة 25-30°م، بقاء الأوراق مبللة طويلًا، زراعة الذرة بشكل متواصل. الزراعة بدون حرث + ذرة متواصلة + زراعة كثيفة.',
      chemicalTreatmentEn: 'Propiconazole, mancozeb, or strobilurins (FRAC 11) applied at VT-R1 when lesions cover 2-3% of lower leaves.',
      chemicalTreatmentAr: 'بروبيكونازول أو مانكوزيب أو ستروبيلورينات (FRAC 11) عند مرحلة VT-R1 عندما تصيب البقع 2-3% من الأوراق السفلية.',
      organicTreatmentEn: 'Crop rotation (1-2 years), tillage to bury residue, resistant hybrids.',
      organicTreatmentAr: 'دورة زراعية (1-2 سنة)، حرث لدفن البقايا، هجن مقاومة.',
      preventionEn: 'Plant resistant hybrids, rotate with non-host crops, avoid excessive no-till in high-risk fields.',
      preventionAr: 'زراعة هجن مقاومة، التناوب مع محاصيل غير عائلة، تجنب الاعتماد المفرط على عدم الحرث في الحقول عالية الخطورة.',
      severity: 'High', seasonEn: 'Mid to late summer', seasonAr: 'منتصف إلى أواخر الصيف',
      sourceUrl: 'https://extension.umn.edu/corn-pest-management/gray-leaf-spot-corn',
    ),
    'Corn_(maize)___Common_rust_': DiseaseInfo(
      cropEn: 'Corn (Maize)', cropAr: 'ذرة',
      diseaseEn: 'Common Rust', diseaseAr: 'الصدأ الشائع',
      isHealthy: false,
      pathogenEn: 'Fungus: Puccinia sorghi', pathogenAr: 'فطر: Puccinia sorghi',
      symptomsEn: 'Chlorotic flecks developing into brick-red, powdery, oval pustules on both leaf surfaces; pustules ~3mm long.',
      symptomsAr: 'نقط صفراء تتطور إلى بثرات بودرية بيضاوية لون طوب أحمر على سطحي الورقة، حجم البثرة حوالي 3 مم.',
      causesEn: 'Cool (16-23°C) and humid conditions (100% humidity for 6+ hours); spores carried from southern regions by wind. Susceptible hybrids and cool weather during silking stage.',
      causesAr: 'ظروف باردة (16-23°م) ورطبة (رطوبة 100% لأكثر من 6 ساعات)، الأبواغ تُحمل من المناطق الجنوبية بالرياح. الهجن القابلة للإصابة والطقس البارد خلال مرحلة تكوين الحرير.',
      chemicalTreatmentEn: 'Strobilurins or triazoles (propiconazole, azoxystrobin) applied early when few pustules present.',
      chemicalTreatmentAr: 'ستروبيلورينات أو تريازولات (بروبيكونازول، أزوكسيستروبين) تطبَّق مبكرًا عند وجود عدد قليل من البثرات.',
      organicTreatmentEn: 'Usually not needed in field corn; use resistant hybrids.',
      organicTreatmentAr: 'غالبًا لا حاجة لذلك في ذرة الحقل، يُكتفى باستخدام هجن مقاومة.',
      preventionEn: 'Use resistant hybrids (Rp-genes); scout early; fungicide only if disease appears before tasseling.',
      preventionAr: 'استخدام هجن مقاومة (جينات Rp)، الكشف المبكر، تطبيق المبيد فقط إذا ظهر المرض قبل التزهير الذكري.',
      severity: 'Medium', seasonEn: 'Early to mid summer', seasonAr: 'بداية إلى منتصف الصيف',
      sourceUrl: 'https://extension.umn.edu/corn-pest-management/common-rust-corn',
    ),
    'Corn_(maize)___Northern_Leaf_Blight': DiseaseInfo(
      cropEn: 'Corn (Maize)', cropAr: 'ذرة',
      diseaseEn: 'Northern Corn Leaf Blight', diseaseAr: 'لفحة الذرة الشمالية',
      isHealthy: false,
      pathogenEn: 'Fungus: Exserohilum turcicum', pathogenAr: 'فطر: Exserohilum turcicum',
      symptomsEn: 'Long, cigar-shaped, grayish-green to tan lesions (2-15 cm) parallel to leaf margins; dark spores visible with hand lens.',
      symptomsAr: 'بقع طويلة على شكل سيجار، رمادية-خضراء إلى بنية فاتحة (2-15 سم) موازية لحواف الورقة، يمكن رؤية الأبواغ الداكنة بالعدسة.',
      causesEn: 'Moderate temperatures (18-27°C), high humidity, heavy dews, extended leaf wetness >6 hours. Continuous corn, susceptible hybrids, reduced tillage.',
      causesAr: 'حرارة معتدلة (18-27°م)، رطوبة عالية، ندى كثيف، بقاء الأوراق مبللة أكثر من 6 ساعات. الذرة المتواصلة، الهجن القابلة للإصابة، الحرث المحدود.',
      chemicalTreatmentEn: 'Flutriafol, propiconazole, or pyraclostrobin from V8 to tasseling stage under high pressure.',
      chemicalTreatmentAr: 'Flutriafol أو بروبيكونازول أو بيراكلوستروبين من مرحلة V8 حتى التزهير تحت ضغط مرض عالٍ.',
      organicTreatmentEn: 'Crop rotation + tillage + resistant hybrids; no effective organic spray.',
      organicTreatmentAr: 'دورة زراعية + حرث + هجن مقاومة؛ لا يوجد رش عضوي فعال.',
      preventionEn: 'Plant resistant hybrids (Ht1, Ht2, Ht3, HtN genes), rotate crops, plow under residue.',
      preventionAr: 'زراعة هجن مقاومة (جينات Ht1, Ht2, Ht3, HtN)، التناوب المحصولي، حرث البقايا.',
      severity: 'High', seasonEn: 'Mid to late summer', seasonAr: 'منتصف إلى أواخر الصيف',
      sourceUrl: 'https://extension.umn.edu/corn-pest-management/northern-corn-leaf-blight',
    ),
    'Corn_(maize)___healthy': DiseaseInfo(
      cropEn: 'Corn (Maize)', cropAr: 'ذرة',
      diseaseEn: 'Healthy', diseaseAr: 'سليم', isHealthy: true,
      pathogenEn: 'None', pathogenAr: 'لا يوجد',
      symptomsEn: _hSymptomsEn, symptomsAr: _hSymptomsAr,
      causesEn: _hCausesEn, causesAr: _hCausesAr,
      chemicalTreatmentEn: _hChemEn, chemicalTreatmentAr: _hChemAr,
      organicTreatmentEn: _hOrgEn, organicTreatmentAr: _hOrgAr,
      preventionEn: _hPrevEn, preventionAr: _hPrevAr,
      severity: 'None', seasonEn: 'All seasons', seasonAr: 'جميع المواسم',
      sourceUrl: 'https://www.apsnet.org/edcenter/Pages/default.aspx',
    ),
    'Grape___Black_rot': DiseaseInfo(
      cropEn: 'Grape', cropAr: 'عنب',
      diseaseEn: 'Black Rot', diseaseAr: 'العفن الأسود',
      isHealthy: false,
      pathogenEn: 'Fungus: Guignardia bidwellii', pathogenAr: 'فطر: Guignardia bidwellii',
      symptomsEn: 'Small yellow leaf spots enlarging to lesions with reddish-brown borders and tan centers with ringed black pycnidia; berries shrivel into black mummies.',
      symptomsAr: 'بقع صفراء صغيرة على الأوراق تتسع إلى بقع بإطار بني محمر ومركز فاتح مع نقاط سوداء دائرية (pycnidia)؛ الحبات تتحول إلى مومياء سوداء مجففة.',
      causesEn: 'Warm (20-32°C) and humid weather; 6+ hours of wetness needed. Infected mummies from prior year left on vines/ground are the main inoculum source.',
      causesAr: 'طقس دافئ (20-32°م) ورطب؛ يحتاج إلى بلل مستمر 6 ساعات أو أكثر. المومياوات المصابة من العام السابق المتروكة على الكرمة/الأرض هي المصدر الرئيسي.',
      chemicalTreatmentEn: 'Mancozeb, myclobutanil, or pyraclostrobin from 2-3 weeks before bloom through 4-6 weeks after bloom.',
      chemicalTreatmentAr: 'مانكوزيب أو مايكلوبوتانيل أو بيراكلوستروبين من 2-3 أسابيع قبل التزهير حتى 4-6 أسابيع بعده.',
      organicTreatmentEn: 'Copper, sulfur sprays; remove all mummies before spring bud break.',
      organicTreatmentAr: 'رش النحاس أو الكبريت، إزالة جميع المومياوات قبل تفتح البراعم الربيعية.',
      preventionEn: 'Sanitation (remove mummies and debris), canopy management for airflow, protective fungicide program.',
      preventionAr: 'النظافة (إزالة المومياوات والبقايا)، إدارة المجموع الخضري للتهوية، برنامج مبيدات وقائية.',
      severity: 'High', seasonEn: 'Spring to early summer', seasonAr: 'الربيع إلى بداية الصيف',
      sourceUrl: 'https://ohioline.osu.edu/factsheet/plpath-fru-24',
    ),
    'Grape___Esca_(Black_Measles)': DiseaseInfo(
      cropEn: 'Grape', cropAr: 'عنب',
      diseaseEn: 'Esca (Black Measles)', diseaseAr: 'إسكا (الحصبة السوداء)',
      isHealthy: false,
      pathogenEn: 'Fungal complex: Phaeoacremonium spp. + Phaeomoniella chlamydospora + Fomitiporia mediterranea',
      pathogenAr: 'مجموعة فطرية: Phaeoacremonium spp. + Phaeomoniella chlamydospora + Fomitiporia mediterranea',
      symptomsEn: 'Interveinal "tiger stripe" pattern on leaves; dark spots on berries; internal wood darkening.',
      symptomsAr: 'نمط "خطوط النمر" بين العروق (أصفر في الأصناف البيضاء، أحمر في الأصناف الحمراء)، بقع داكنة على الحبات، سواد داخلي في الخشب.',
      causesEn: 'Pathogens enter via pruning wounds; infection favored by wet weather after pruning. Drought stress + pruning wounds during wet weather; old vines (>10 years) more susceptible.',
      causesAr: 'المسببات تدخل عبر جروح التقليم؛ العدوى تنشط في طقس رطب بعد التقليم. إجهاد الجفاف + جروح التقليم في الطقس الرطب؛ الكرمات القديمة (>10 سنوات) أكثر قابلية.',
      chemicalTreatmentEn: 'Only thiophanate-methyl approved for wound protection; no cure once vine is systemic.',
      chemicalTreatmentAr: 'ثيوفانات ميثيل فقط مسموح به لحماية الجروح؛ لا يوجد علاج بعد إصابة الكرمة جهازيًا.',
      organicTreatmentEn: 'Trichoderma-based biocontrol paints on pruning wounds; trunk renewal (cut infected section and retrain).',
      organicTreatmentAr: 'دهانات حيوية ببكتيريا Trichoderma على جروح التقليم، تجديد الجذع (قطع الجزء المصاب وإعادة التربية).',
      preventionEn: 'Prune during dry weather; protect pruning wounds; avoid large cuts on older vines; remove symptomatic vines.',
      preventionAr: 'التقليم في الجو الجاف، حماية جروح التقليم، تجنب القطوع الكبيرة في الكرمات الكبيرة، إزالة الكرمات المريضة.',
      severity: 'High', seasonEn: 'Symptoms appear July–August', seasonAr: 'الأعراض تظهر يوليو-أغسطس',
      sourceUrl: 'https://ipm.ucanr.edu/agriculture/grape/esca-black-measles/',
    ),
    'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)': DiseaseInfo(
      cropEn: 'Grape', cropAr: 'عنب',
      diseaseEn: 'Leaf Blight (Isariopsis Leaf Spot)', diseaseAr: 'لفحة الأوراق (بقعة إزاريوبسيز)',
      isHealthy: false,
      pathogenEn: 'Fungus: Pseudocercospora vitis', pathogenAr: 'فطر: Pseudocercospora vitis',
      symptomsEn: 'Large irregular spots, initially dull red to brown, turning black and brittle with age. Usually appears late in season.',
      symptomsAr: 'بقع كبيرة غير منتظمة، تبدأ حمراء باهتة إلى بنية، ثم تسودّ وتصبح هشة. عادة تظهر أواخر الموسم.',
      causesEn: 'Warm, humid conditions late in the growing season; poor spray coverage. Neglected or poorly sprayed vineyards; late-season vigor loss.',
      causesAr: 'ظروف دافئة ورطبة أواخر الموسم، ضعف تغطية الرش. كروم مهملة أو ضعيفة الرش، ضعف نشاط الكرمة أواخر الموسم.',
      chemicalTreatmentEn: 'Copper fungicides (Bordeaux mixture) applied late in season after fruiting.',
      chemicalTreatmentAr: 'مبيدات نحاسية (مخلوط بوردو) تطبَّق أواخر الموسم بعد الإثمار.',
      organicTreatmentEn: 'Copper sprays; lemongrass essential oil has shown efficacy in trials.',
      organicTreatmentAr: 'رش النحاس، زيت الليمون الأساسي أثبت فعالية في التجارب.',
      preventionEn: 'Canopy management (shoot thinning, leaf removal), maintain regular fungicide schedule through late season.',
      preventionAr: 'إدارة المجموع الخضري (تقليم الأفرع، إزالة الأوراق)، الحفاظ على جدول مبيدات منتظم حتى أواخر الموسم.',
      severity: 'Low', seasonEn: 'Late summer to fall', seasonAr: 'أواخر الصيف إلى الخريف',
      sourceUrl: 'https://plantvillage.psu.edu/topics/grape/infos/diseases_and_pests_description_uses_propagation',
    ),
    'Grape___healthy': DiseaseInfo(
      cropEn: 'Grape', cropAr: 'عنب',
      diseaseEn: 'Healthy', diseaseAr: 'سليم', isHealthy: true,
      pathogenEn: 'None', pathogenAr: 'لا يوجد',
      symptomsEn: _hSymptomsEn, symptomsAr: _hSymptomsAr,
      causesEn: _hCausesEn, causesAr: _hCausesAr,
      chemicalTreatmentEn: _hChemEn, chemicalTreatmentAr: _hChemAr,
      organicTreatmentEn: _hOrgEn, organicTreatmentAr: _hOrgAr,
      preventionEn: _hPrevEn, preventionAr: _hPrevAr,
      severity: 'None', seasonEn: 'All seasons', seasonAr: 'جميع المواسم',
      sourceUrl: 'https://www.apsnet.org/edcenter/Pages/default.aspx',
    ),
    'Orange___Haunglongbing_(Citrus_greening)': DiseaseInfo(
      cropEn: 'Orange (Citrus)', cropAr: 'برتقال (موالح)',
      diseaseEn: 'Huanglongbing (Citrus Greening)', diseaseAr: 'هوانجلونجبينج (التخضّر)',
      isHealthy: false,
      pathogenEn: 'Bacterium: Candidatus Liberibacter asiaticus; vectored by Asian citrus psyllid Diaphorina citri',
      pathogenAr: 'بكتيريا: Candidatus Liberibacter asiaticus؛ ينقلها حشرة بسيلا الحمضيات الآسيوية Diaphorina citri',
      symptomsEn: 'Asymmetric blotchy mottle on leaves, yellow veins, small lopsided bitter fruit with green ends, premature fruit drop, eventual tree death.',
      symptomsAr: 'تبقع متبقّع غير متماثل على الأوراق، اصفرار العروق، ثمار صغيرة غير منتظمة الشكل مريرة الطعم خضراء الأطراف، تساقط مبكر للثمار، وموت الشجرة في النهاية.',
      causesEn: 'Warm regions favor psyllid populations. Proximity to infected trees or nurseries; any psyllid infestation in orchard.',
      causesAr: 'المناطق الدافئة مفضّلة لتكاثر البسيلا. القرب من أشجار أو مشاتل مصابة، أي إصابة بالبسيلا في البستان.',
      chemicalTreatmentEn: 'No cure. Control psyllids with imidacloprid, thiamethoxam, or pyrethroids (rotate to avoid resistance).',
      chemicalTreatmentAr: 'لا يوجد علاج. مكافحة البسيلا بـ إيميداكلوبريد أو ثياميثوكسام أو بيرثرويدات (مع التبديل لمنع المقاومة).',
      organicTreatmentEn: 'Horticultural oils, kaolin clay, neem oil for psyllid control; biocontrol with Tamarixia radiata wasp.',
      organicTreatmentAr: 'زيوت بستانية، طين الكاولين، زيت النيم لمكافحة البسيلا، المكافحة الحيوية باستخدام زنبور Tamarixia radiata.',
      preventionEn: 'Use certified disease-free nursery stock; remove infected trees immediately; scout for psyllids weekly; area-wide management.',
      preventionAr: 'استخدام شتلات معتمدة خالية من المرض، إزالة الأشجار المصابة فورًا، الكشف الأسبوعي عن البسيلا، إدارة شاملة للمنطقة.',
      severity: 'High', seasonEn: 'Year-round in warm climates', seasonAr: 'طوال العام في المناخات الدافئة',
      sourceUrl: 'https://crec.ifas.ufl.edu/research/citrus-production/disease-identification/citrus-greening-huanglongbing/',
    ),
    'Peach___Bacterial_spot': DiseaseInfo(
      cropEn: 'Peach', cropAr: 'خوخ',
      diseaseEn: 'Bacterial Spot', diseaseAr: 'التبقع البكتيري',
      isHealthy: false,
      pathogenEn: 'Bacterium: Xanthomonas arboricola pv. pruni', pathogenAr: 'بكتيريا: Xanthomonas arboricola pv. pruni',
      symptomsEn: 'Small angular water-soaked leaf spots turning purple-brown then dropping out ("shot-hole" look); fruit cracks; twig cankers.',
      symptomsAr: 'بقع زاوية صغيرة مشبعة بالماء على الأوراق تتحول لبني بنفسجي ثم تسقط (مظهر ثقب الطلقة)، تشقق الثمار، تقرحات على الأفرع.',
      causesEn: 'Warm, wet weather (24-29°C); wind-driven rain; overhead irrigation. Sandy soils, weak tree vigor, poor nutrition (especially low K and Zn).',
      causesAr: 'طقس دافئ رطب (24-29°م)، مطر مصحوب برياح، ري علوي. تربة رملية، ضعف نمو الشجرة، تغذية ضعيفة (خاصة البوتاسيوم والزنك).',
      chemicalTreatmentEn: 'Copper sprays at dormant/shuck-split, reducing rate to avoid foliar burn; oxytetracycline in severe cases.',
      chemicalTreatmentAr: 'رش النحاس في مرحلة السكون/انشقاق القشرة، مع تخفيض الجرعة لتجنب حرق الأوراق، أوكسي تتراسيكلين في الحالات الشديدة.',
      organicTreatmentEn: 'Copper hydroxide at dormancy; plant resistant varieties (Contender, Redhaven, Harrow Diamond).',
      organicTreatmentAr: 'هيدروكسيد النحاس في مرحلة السكون، زراعة أصناف مقاومة (Contender, Redhaven, Harrow Diamond).',
      preventionEn: 'Resistant cultivars, avoid overhead irrigation, prune during dry weather, ensure balanced fertilization (adequate K and Zn).',
      preventionAr: 'أصناف مقاومة، تجنب الري العلوي، التقليم في طقس جاف، التسميد المتوازن (خاصة البوتاسيوم والزنك).',
      severity: 'High', seasonEn: 'Spring to early summer', seasonAr: 'الربيع إلى بداية الصيف',
      sourceUrl: 'https://extension.psu.edu/stone-fruit-disease-bacterial-spot',
    ),
    'Peach___healthy': DiseaseInfo(
      cropEn: 'Peach', cropAr: 'خوخ',
      diseaseEn: 'Healthy', diseaseAr: 'سليم', isHealthy: true,
      pathogenEn: 'None', pathogenAr: 'لا يوجد',
      symptomsEn: _hSymptomsEn, symptomsAr: _hSymptomsAr,
      causesEn: _hCausesEn, causesAr: _hCausesAr,
      chemicalTreatmentEn: _hChemEn, chemicalTreatmentAr: _hChemAr,
      organicTreatmentEn: _hOrgEn, organicTreatmentAr: _hOrgAr,
      preventionEn: _hPrevEn, preventionAr: _hPrevAr,
      severity: 'None', seasonEn: 'All seasons', seasonAr: 'جميع المواسم',
      sourceUrl: 'https://www.apsnet.org/edcenter/Pages/default.aspx',
    ),
    'Pepper,_bell___Bacterial_spot': DiseaseInfo(
      cropEn: 'Bell Pepper', cropAr: 'فلفل رومي',
      diseaseEn: 'Bacterial Spot', diseaseAr: 'التبقع البكتيري',
      isHealthy: false,
      pathogenEn: 'Bacteria: Xanthomonas euvesicatoria, X. vesicatoria, X. gardneri, X. perforans',
      pathogenAr: 'بكتيريا: Xanthomonas euvesicatoria و X. vesicatoria و X. gardneri و X. perforans',
      symptomsEn: 'Small (<3 mm) brown circular leaf spots without yellow halo; fruit shows raised brown scabs.',
      symptomsAr: 'بقع دائرية بنية صغيرة (<3 مم) على الأوراق بدون هالة صفراء، بقع بنية مرتفعة على الثمار.',
      causesEn: 'Warm (24-30°C), humid, rainy weather; seed-borne inoculum; contaminated tools. Overhead watering, dense planting, infected seed or transplants.',
      causesAr: 'طقس دافئ (24-30°م) رطب ممطر، بذور ملوثة، أدوات ملوثة. الري العلوي، الزراعة الكثيفة، شتلات أو بذور مصابة.',
      chemicalTreatmentEn: 'Copper + mancozeb tank mix every 7-10 days; copper resistance is common, so rotate with streptomycin where allowed.',
      chemicalTreatmentAr: 'خليط نحاس + مانكوزيب كل 7-10 أيام، مقاومة النحاس شائعة فاستبدلها بـ ستربتومايسين عند السماح.',
      organicTreatmentEn: 'Copper hydroxide; hot water seed treatment (50°C for 25 min); Serenade (Bacillus subtilis).',
      organicTreatmentAr: 'هيدروكسيد النحاس، معالجة البذور بالماء الساخن (50°م لمدة 25 دقيقة)، Serenade (Bacillus subtilis).',
      preventionEn: 'Use certified disease-free seed/transplants; drip irrigation; 2-3 year rotation; resistant cultivars.',
      preventionAr: 'استخدام بذور/شتلات معتمدة خالية من المرض، ري بالتنقيط، دورة زراعية 2-3 سنوات، أصناف مقاومة.',
      severity: 'High', seasonEn: 'Warm summer months', seasonAr: 'أشهر الصيف الدافئة',
      sourceUrl: 'https://extension.umn.edu/disease-management/bacterial-spot-tomato-and-pepper',
    ),
    'Pepper,_bell___healthy': DiseaseInfo(
      cropEn: 'Bell Pepper', cropAr: 'فلفل رومي',
      diseaseEn: 'Healthy', diseaseAr: 'سليم', isHealthy: true,
      pathogenEn: 'None', pathogenAr: 'لا يوجد',
      symptomsEn: _hSymptomsEn, symptomsAr: _hSymptomsAr,
      causesEn: _hCausesEn, causesAr: _hCausesAr,
      chemicalTreatmentEn: _hChemEn, chemicalTreatmentAr: _hChemAr,
      organicTreatmentEn: _hOrgEn, organicTreatmentAr: _hOrgAr,
      preventionEn: _hPrevEn, preventionAr: _hPrevAr,
      severity: 'None', seasonEn: 'All seasons', seasonAr: 'جميع المواسم',
      sourceUrl: 'https://www.apsnet.org/edcenter/Pages/default.aspx',
    ),
    'Potato___Early_blight': DiseaseInfo(
      cropEn: 'Potato', cropAr: 'بطاطس',
      diseaseEn: 'Early Blight', diseaseAr: 'اللفحة المبكرة',
      isHealthy: false,
      pathogenEn: 'Fungus: Alternaria solani', pathogenAr: 'فطر: Alternaria solani',
      symptomsEn: 'Dark brown lesions with concentric rings (target-like) on older leaves first; papery and sunken; tuber lesions are dark, sunken with corky flesh beneath.',
      symptomsAr: 'بقع بنية داكنة بحلقات دائرية (تشبه الهدف) تبدأ بالأوراق القديمة، تصبح ورقية وغائرة، بقع الدرنات داكنة غائرة مع لحم فليني تحتها.',
      causesEn: 'Warm (24-29°C) temperatures with alternating wet-dry periods; attacks stressed or senescing plants. Nitrogen deficiency, drought stress, heavy fruit load.',
      causesAr: 'حرارة 24-29°م مع تناوب فترات الرطب والجاف، يهاجم النباتات المجهدة. نقص الآزوت، إجهاد الجفاف، حمل ثمري ثقيل.',
      chemicalTreatmentEn: 'Chlorothalonil, mancozeb, or azoxystrobin on a 7-14 day schedule starting at row closure.',
      chemicalTreatmentAr: 'كلوروثالونيل أو مانكوزيب أو أزوكسيستروبين كل 7-14 يوم بدءًا من انغلاق الصفوف.',
      organicTreatmentEn: 'Copper sprays; Bacillus subtilis (Serenade); compost tea; maintain proper N fertilization.',
      organicTreatmentAr: 'رش النحاس، Bacillus subtilis (Serenade)، شاي الكمبوست، تسميد آزوتي مناسب.',
      preventionEn: 'Maintain plant vigor with balanced fertilization; 2-3 year crop rotation; avoid overhead irrigation; remove volunteer potatoes.',
      preventionAr: 'الحفاظ على نشاط النبات بتسميد متوازن، دورة زراعية 2-3 سنوات، تجنب الري العلوي، إزالة نباتات البطاطس العفوية.',
      severity: 'Medium', seasonEn: 'Mid to late growing season', seasonAr: 'منتصف إلى أواخر الموسم',
      sourceUrl: 'https://extension.umn.edu/disease-management/early-blight-tomato-and-potato',
    ),
    'Potato___Late_blight': DiseaseInfo(
      cropEn: 'Potato', cropAr: 'بطاطس',
      diseaseEn: 'Late Blight', diseaseAr: 'اللفحة المتأخرة',
      isHealthy: false,
      pathogenEn: 'Oomycete: Phytophthora infestans', pathogenAr: 'عضو الأومِسيتات: Phytophthora infestans',
      symptomsEn: 'Irregular water-soaked lesions on leaves turning dark brown; white fuzzy sporulation on leaf undersides; stem lesions; tuber rot with reddish-brown granular flesh.',
      symptomsAr: 'بقع مشبعة بالماء غير منتظمة على الأوراق تتحول بنية داكنة، زغب أبيض من الأسفل، بقع على السيقان، تعفن الدرنات مع لحم حبيبي بني محمر.',
      causesEn: 'Cool (15-20°C), wet, foggy, humid weather. Dense planting, irrigation at dusk, infected seed tubers.',
      causesAr: 'طقس بارد (15-20°م) رطب ضبابي. زراعة كثيفة، ري قبل المغيب، درنات بذار مصابة.',
      chemicalTreatmentEn: 'Protectants (mancozeb, chlorothalonil) + translaminar (cymoxanil, mandipropamid) on 5-7 day schedule under pressure.',
      chemicalTreatmentAr: 'مبيدات وقائية (مانكوزيب، كلوروثالونيل) + جهازية (cymoxanil, mandipropamid) كل 5-7 أيام تحت الضغط.',
      organicTreatmentEn: 'Copper hydroxide on a preventive 5-day schedule; destroy infected plants immediately.',
      organicTreatmentAr: 'هيدروكسيد النحاس كرش وقائي كل 5 أيام، إتلاف النباتات المصابة فورًا.',
      preventionEn: 'Certified clean seed, resistant varieties (Defender, Sarpo Mira), destroy cull piles, monitor forecasts.',
      preventionAr: 'بذور معتمدة نظيفة، أصناف مقاومة (Defender, Sarpo Mira)، إتلاف أكوام البطاطس المستبعدة، متابعة التنبؤات.',
      severity: 'High', seasonEn: 'Cool wet seasons (spring/fall)', seasonAr: 'المواسم الباردة الرطبة (ربيع/خريف)',
      sourceUrl: 'https://extension.umn.edu/disease-management/late-blight',
    ),
    'Potato___healthy': DiseaseInfo(
      cropEn: 'Potato', cropAr: 'بطاطس',
      diseaseEn: 'Healthy', diseaseAr: 'سليم', isHealthy: true,
      pathogenEn: 'None', pathogenAr: 'لا يوجد',
      symptomsEn: _hSymptomsEn, symptomsAr: _hSymptomsAr,
      causesEn: _hCausesEn, causesAr: _hCausesAr,
      chemicalTreatmentEn: _hChemEn, chemicalTreatmentAr: _hChemAr,
      organicTreatmentEn: _hOrgEn, organicTreatmentAr: _hOrgAr,
      preventionEn: _hPrevEn, preventionAr: _hPrevAr,
      severity: 'None', seasonEn: 'All seasons', seasonAr: 'جميع المواسم',
      sourceUrl: 'https://www.apsnet.org/edcenter/Pages/default.aspx',
    ),
    'Raspberry___healthy': DiseaseInfo(
      cropEn: 'Raspberry', cropAr: 'توت العُلّيق',
      diseaseEn: 'Healthy', diseaseAr: 'سليم', isHealthy: true,
      pathogenEn: 'None', pathogenAr: 'لا يوجد',
      symptomsEn: _hSymptomsEn, symptomsAr: _hSymptomsAr,
      causesEn: _hCausesEn, causesAr: _hCausesAr,
      chemicalTreatmentEn: _hChemEn, chemicalTreatmentAr: _hChemAr,
      organicTreatmentEn: _hOrgEn, organicTreatmentAr: _hOrgAr,
      preventionEn: _hPrevEn, preventionAr: _hPrevAr,
      severity: 'None', seasonEn: 'All seasons', seasonAr: 'جميع المواسم',
      sourceUrl: 'https://www.apsnet.org/edcenter/Pages/default.aspx',
    ),
    'Rice___Brown_spot': DiseaseInfo(
      cropEn: 'Rice', cropAr: 'أرز',
      diseaseEn: 'Brown Spot', diseaseAr: 'البقعة البنية',
      isHealthy: false,
      pathogenEn: 'Fungus: Bipolaris oryzae', pathogenAr: 'فطر: Bipolaris oryzae',
      symptomsEn: 'Circular to oval brown spots with gray centers and reddish-brown margins on leaves; can also infect glumes, grains, sheaths. Up to 45% yield loss.',
      symptomsAr: 'بقع بنية دائرية إلى بيضاوية بمركز رمادي وحواف بنية محمرة على الأوراق، يصيب كذلك الغلاف والحبوب والأكمام، يسبب خسائر محصول تصل إلى 45%.',
      causesEn: 'Heat (25-30°C), high humidity, prolonged leaf wetness. Soil nutrient deficiency (especially N, K, silicon); sandy/saline soils; drought stress.',
      causesAr: 'حرارة 25-30°م، رطوبة عالية، بقاء الأوراق مبللة. نقص مغذيات التربة (خاصة N و K و السيليكون)، تربة رملية/مالحة، إجهاد جفاف.',
      chemicalTreatmentEn: 'Propiconazole, iprodione, or mancozeb; seed treatment with carbendazim or thiram.',
      chemicalTreatmentAr: 'بروبيكونازول أو إيبروديون أو مانكوزيب، معالجة البذور بالكاربندازيم أو الثيرام.',
      organicTreatmentEn: 'Apply balanced NPK + silicon; use green manure; hot water seed treatment (53-54°C, 12 min).',
      organicTreatmentAr: 'تسميد متوازن NPK + سيليكون، استخدام السماد الأخضر، معالجة البذور بالماء الساخن (53-54°م، 12 دقيقة).',
      preventionEn: 'Fix soil fertility first! Use resistant varieties; clean seed; balanced fertilization including potassium and silicon.',
      preventionAr: 'أصلح خصوبة التربة أولًا! استخدم أصناف مقاومة، بذور نظيفة، تسميد متوازن يشمل البوتاسيوم والسيليكون.',
      severity: 'High', seasonEn: 'All rice growing seasons', seasonAr: 'جميع مواسم زراعة الأرز',
      sourceUrl: 'http://www.knowledgebank.irri.org/training/fact-sheets/pest-management/diseases/item/brown-spot',
    ),
    'Rice___Healthy': DiseaseInfo(
      cropEn: 'Rice', cropAr: 'أرز',
      diseaseEn: 'Healthy', diseaseAr: 'سليم', isHealthy: true,
      pathogenEn: 'None', pathogenAr: 'لا يوجد',
      symptomsEn: _hSymptomsEn, symptomsAr: _hSymptomsAr,
      causesEn: _hCausesEn, causesAr: _hCausesAr,
      chemicalTreatmentEn: _hChemEn, chemicalTreatmentAr: _hChemAr,
      organicTreatmentEn: _hOrgEn, organicTreatmentAr: _hOrgAr,
      preventionEn: _hPrevEn, preventionAr: _hPrevAr,
      severity: 'None', seasonEn: 'All seasons', seasonAr: 'جميع المواسم',
      sourceUrl: 'https://www.apsnet.org/edcenter/Pages/default.aspx',
    ),
    'Rice___Hispa': DiseaseInfo(
      cropEn: 'Rice', cropAr: 'أرز',
      diseaseEn: 'Rice Hispa (Insect Pest)', diseaseAr: 'هِسبا الأرز (آفة حشرية)',
      isHealthy: false,
      pathogenEn: 'Insect (beetle): Dicladispa armigera', pathogenAr: 'حشرة (خنفساء): Dicladispa armigera',
      symptomsEn: 'White parallel streaks along leaf veins from surface scraping by adults; translucent patches from larval tunneling. Up to 20% yield loss.',
      symptomsAr: 'خطوط بيضاء موازية لعروق الأوراق من كشط البالغين للسطح، بقع شفافة من أنفاق اليرقات، خسائر محصول تصل إلى 20%.',
      causesEn: 'Warm humid weather; weedy bunds; high nitrogen applications favor outbreaks. Over-fertilization with nitrogen; wide plant spacing; weedy field borders.',
      causesAr: 'طقس دافئ رطب، جسور حقول مليئة بالحشائش، التسميد الآزوتي المفرط يزيد تفشيها. الإفراط في التسميد الآزوتي، مسافات زراعة واسعة.',
      chemicalTreatmentEn: 'Chlorpyrifos, quinalphos, or monocrotophos when damage exceeds threshold; apply to young adult stage.',
      chemicalTreatmentAr: 'كلوربيريفوس أو كوينالفوس أو مونوكروتوفوس عند تجاوز الضرر الحد الاقتصادي، يُطبَّق على مرحلة البالغ الصغير.',
      organicTreatmentEn: 'Clip and bury infested leaf tips (reduces grubs 75-92%); release egg-parasitic wasps; entomopathogenic fungi (Metarhizium).',
      organicTreatmentAr: 'قص ودفن أطراف الأوراق المصابة (يقلل اليرقات 75-92%)، إطلاق طفيليات البيض من الزنابير، فطريات ممرضة للحشرات (Metarhizium).',
      preventionEn: 'Avoid excessive nitrogen; close plant spacing; weed bunds; scout early; use resistant varieties where available.',
      preventionAr: 'تجنب الإفراط في الآزوت، زراعة كثيفة، تنظيف جسور الحقل من الحشائش، الكشف المبكر، أصناف مقاومة حيث تتوفر.',
      severity: 'Medium', seasonEn: 'Wet season (monsoon)', seasonAr: 'الموسم الرطب (الموسمي)',
      sourceUrl: 'http://www.knowledgebank.irri.org/training/fact-sheets/pest-management/insects/item/rice-hispa',
    ),
    'Rice___Leaf_blast': DiseaseInfo(
      cropEn: 'Rice', cropAr: 'أرز',
      diseaseEn: 'Rice Blast (Leaf)', diseaseAr: 'لفحة الأرز (الأوراق)',
      isHealthy: false,
      pathogenEn: 'Fungus: Magnaporthe oryzae', pathogenAr: 'فطر: Magnaporthe oryzae',
      symptomsEn: 'Diamond-shaped spots with gray-white centers and brown borders on leaves; can appear on nodes ("rotten neck") causing whole panicle loss. Most devastating rice disease globally.',
      symptomsAr: 'بقع ماسية الشكل بمركز رمادي-أبيض وإطار بني على الأوراق، قد تظهر على العقد (رقبة متعفنة) فتسبب خسارة السنبلة كلها. أخطر مرض للأرز عالميًا.',
      causesEn: 'Cool nights, heavy dew, extended leaf wetness >6 hours; low soil moisture; high nitrogen. Excessive nitrogen fertilization (the #1 trigger), drought stress during growing period.',
      causesAr: 'ليالي باردة، ندى كثيف، بقاء الأوراق مبللة >6 ساعات، انخفاض رطوبة التربة، إفراط في الآزوت. الإفراط في التسميد الآزوتي (السبب الأول).',
      chemicalTreatmentEn: 'Tricyclazole, isoprothiolane, azoxystrobin, or carpropamid; apply at tillering and booting stages.',
      chemicalTreatmentAr: 'تريسيكلازول أو إيزوبروثيولان أو أزوكسيستروبين أو كاربروباميد، يُطبَّق في مرحلة التفريع والتطاول.',
      organicTreatmentEn: 'Silicon amendments (harden cell walls); balanced nitrogen (split applications); resistant varieties.',
      organicTreatmentAr: 'إضافة السيليكون (يقوي جدران الخلايا)، تسميد آزوتي متوازن (جرعات مقسمة)، أصناف مقاومة.',
      preventionEn: 'Split nitrogen applications; maintain flooding; use blast-resistant varieties (IR64, Tetep); clean seed; destroy stubble.',
      preventionAr: 'تسميد آزوتي على جرعات، الحفاظ على الغمر، استخدام أصناف مقاومة للبلاست (IR64, Tetep)، بذور نظيفة، إتلاف القش.',
      severity: 'High', seasonEn: 'Cool humid periods; both wet and dry seasons', seasonAr: 'الفترات الباردة الرطبة، في كل من الموسمين الرطب والجاف',
      sourceUrl: 'http://www.knowledgebank.irri.org/training/fact-sheets/pest-management/diseases/item/blast-leaf-collar',
    ),
    'Soybean___healthy': DiseaseInfo(
      cropEn: 'Soybean', cropAr: 'فول الصويا',
      diseaseEn: 'Healthy', diseaseAr: 'سليم', isHealthy: true,
      pathogenEn: 'None', pathogenAr: 'لا يوجد',
      symptomsEn: _hSymptomsEn, symptomsAr: _hSymptomsAr,
      causesEn: _hCausesEn, causesAr: _hCausesAr,
      chemicalTreatmentEn: _hChemEn, chemicalTreatmentAr: _hChemAr,
      organicTreatmentEn: _hOrgEn, organicTreatmentAr: _hOrgAr,
      preventionEn: _hPrevEn, preventionAr: _hPrevAr,
      severity: 'None', seasonEn: 'All seasons', seasonAr: 'جميع المواسم',
      sourceUrl: 'https://www.apsnet.org/edcenter/Pages/default.aspx',
    ),
    'Squash___Powdery_mildew': DiseaseInfo(
      cropEn: 'Squash', cropAr: 'قرع (كوسة)',
      diseaseEn: 'Powdery Mildew', diseaseAr: 'البياض الدقيقي',
      isHealthy: false,
      pathogenEn: 'Fungi: Podosphaera xanthii and Erysiphe cichoracearum',
      pathogenAr: 'فطر: Podosphaera xanthii و Erysiphe cichoracearum',
      symptomsEn: 'White powdery spots on upper and lower leaf surfaces, petioles, and stems; leaves yellow and die prematurely; reduces fruit quality.',
      symptomsAr: 'بقع بيضاء دقيقية على سطحي الورقة والأعناق والسيقان، اصفرار الأوراق وموتها المبكر، انخفاض جودة الثمار.',
      causesEn: 'Warm days (20-27°C) with high humidity but dry leaf surfaces; shaded conditions; low light. Excessive nitrogen, dense planting, poor air circulation.',
      causesAr: 'نهار دافئ (20-27°م) مع رطوبة عالية لكن أوراق جافة، ظروف مظللة. إفراط في الآزوت، زراعة كثيفة، ضعف التهوية.',
      chemicalTreatmentEn: 'Chlorothalonil (FRAC M05), myclobutanil, or sulfur at first sign; rotate FRAC groups.',
      chemicalTreatmentAr: 'كلوروثالونيل (FRAC M05)، مايكلوبوتانيل، أو الكبريت عند أول ظهور، مع تبديل مجموعات الـ FRAC.',
      organicTreatmentEn: 'Potassium bicarbonate (MilStop), sulfur, neem oil, milk solution (1:10), Bacillus subtilis.',
      organicTreatmentAr: 'بيكربونات البوتاسيوم (MilStop)، الكبريت، زيت النيم، محلول الحليب (1:10)، Bacillus subtilis.',
      preventionEn: 'Plant resistant varieties; space plants well; avoid overhead watering; morning irrigation; remove infected leaves.',
      preventionAr: 'أصناف مقاومة، مسافات زراعة مناسبة، تجنب الري العلوي، الري صباحًا، إزالة الأوراق المصابة.',
      severity: 'Medium', seasonEn: 'Mid to late summer', seasonAr: 'منتصف إلى أواخر الصيف',
      sourceUrl: 'https://www.vegetables.cornell.edu/pest-management/disease-factsheets/cucurbit-powdery-mildew/',
    ),
    'Strawberry___Leaf_scorch': DiseaseInfo(
      cropEn: 'Strawberry', cropAr: 'فراولة',
      diseaseEn: 'Leaf Scorch', diseaseAr: 'لفحة الأوراق',
      isHealthy: false,
      pathogenEn: 'Fungus: Diplocarpon earlianum', pathogenAr: 'فطر: Diplocarpon earlianum',
      symptomsEn: 'Small (3-6 mm) purple spots on upper leaf surfaces (no light center); leaves turn brown, dry, curl at margins giving a "scorched" look.',
      symptomsAr: 'بقع صغيرة (3-6 مم) بنفسجية على السطح العلوي للأوراق (بدون مركز فاتح)، الأوراق تتحول بنية جافة ملتفة الأطراف (مظهر محروق).',
      causesEn: 'Warm, wet spring weather; prolonged leaf wetness; splash from soil. Overhead irrigation, late-evening watering, crowded plantings, infected plant debris.',
      causesAr: 'طقس ربيعي دافئ رطب، بقاء الأوراق مبللة، تناثر من التربة. ري علوي، ري في المساء، زراعة كثيفة، بقايا نباتية مصابة من العام السابق.',
      chemicalTreatmentEn: 'Thiophanate-methyl applied starting at bloom, repeated every 2 weeks if wet conditions persist.',
      chemicalTreatmentAr: 'ثيوفانات ميثيل بدءًا من التزهير، يُكرر كل أسبوعين إذا استمرت الظروف الرطبة.',
      organicTreatmentEn: 'Copper sprays; Bacillus subtilis; remove and destroy infected leaves and debris.',
      organicTreatmentAr: 'رش النحاس، Bacillus subtilis، إزالة وإتلاف الأوراق والبقايا المصابة.',
      preventionEn: 'Use drip irrigation; remove debris at end of season; morning watering; resistant varieties (Allstar, Delite, Earliglow).',
      preventionAr: 'ري بالتنقيط، إزالة البقايا أواخر الموسم، الري صباحًا، أصناف مقاومة (Allstar, Delite, Earliglow).',
      severity: 'Medium', seasonEn: 'Spring to early summer', seasonAr: 'الربيع إلى بداية الصيف',
      sourceUrl: 'https://ipm.ucanr.edu/PMG/GARDEN/FRUIT/DISEASE/leafscorch.html',
    ),
    'Strawberry___healthy': DiseaseInfo(
      cropEn: 'Strawberry', cropAr: 'فراولة',
      diseaseEn: 'Healthy', diseaseAr: 'سليم', isHealthy: true,
      pathogenEn: 'None', pathogenAr: 'لا يوجد',
      symptomsEn: _hSymptomsEn, symptomsAr: _hSymptomsAr,
      causesEn: _hCausesEn, causesAr: _hCausesAr,
      chemicalTreatmentEn: _hChemEn, chemicalTreatmentAr: _hChemAr,
      organicTreatmentEn: _hOrgEn, organicTreatmentAr: _hOrgAr,
      preventionEn: _hPrevEn, preventionAr: _hPrevAr,
      severity: 'None', seasonEn: 'All seasons', seasonAr: 'جميع المواسم',
      sourceUrl: 'https://www.apsnet.org/edcenter/Pages/default.aspx',
    ),
    'Tomato___Bacterial_spot': DiseaseInfo(
      cropEn: 'Tomato', cropAr: 'طماطم',
      diseaseEn: 'Bacterial Spot', diseaseAr: 'التبقع البكتيري',
      isHealthy: false,
      pathogenEn: 'Bacteria: Xanthomonas spp. (euvesicatoria, vesicatoria, gardneri, perforans)',
      pathogenAr: 'بكتيريا: Xanthomonas spp.',
      symptomsEn: 'Small dark angular leaf spots with yellow halo; centers fall out giving shot-hole; fruit has raised scabby lesions with water-soaked borders.',
      symptomsAr: 'بقع زاوية داكنة صغيرة على الأوراق بهالة صفراء، مراكزها تسقط (ثقب الطلقة)، بقع مرتفعة خشنة على الثمار بحواف مشبعة بالماء.',
      causesEn: 'Warm (24-30°C) wet weather; splashing rain; contaminated seeds; overhead irrigation. Infected seed/transplants, working plants when wet.',
      causesAr: 'طقس دافئ (24-30°م) رطب، تناثر الأمطار، بذور ملوثة، ري علوي. بذور/شتلات مصابة، العمل مع النباتات وهي مبللة.',
      chemicalTreatmentEn: 'Copper + mancozeb tank mix every 7-10 days; streptomycin on transplants only where permitted.',
      chemicalTreatmentAr: 'خليط النحاس + مانكوزيب كل 7-10 أيام، ستربتومايسين على الشتلات فقط عند السماح.',
      organicTreatmentEn: 'Hot water seed treatment (50°C, 25 min); copper hydroxide; Bacillus subtilis (Serenade).',
      organicTreatmentAr: 'معالجة البذور بالماء الساخن (50°م لمدة 25 دقيقة)، هيدروكسيد النحاس، Bacillus subtilis (Serenade).',
      preventionEn: 'Certified clean seed/transplants; drip irrigation; stake plants; 2-year rotation away from solanaceous crops.',
      preventionAr: 'بذور/شتلات معتمدة نظيفة، ري بالتنقيط، تعريش النباتات، دورة زراعية سنتين بعيدًا عن العائلة الباذنجانية.',
      severity: 'High', seasonEn: 'Warm summer months', seasonAr: 'أشهر الصيف الدافئة',
      sourceUrl: 'https://extension.umn.edu/disease-management/bacterial-spot-tomato-and-pepper',
    ),
    'Tomato___Early_blight': DiseaseInfo(
      cropEn: 'Tomato', cropAr: 'طماطم',
      diseaseEn: 'Early Blight', diseaseAr: 'اللفحة المبكرة',
      isHealthy: false,
      pathogenEn: 'Fungi: Alternaria solani / Alternaria tomatophila',
      pathogenAr: 'فطر: Alternaria solani / Alternaria tomatophila',
      symptomsEn: 'Target-like lesions with concentric rings on older leaves first; yellow halo; stem and fruit lesions at blossom/stem end.',
      symptomsAr: 'بقع بحلقات دائرية (هدفية) على الأوراق القديمة أولًا، بهالة صفراء، بقع على السيقان والثمار من جهة القمة/الذيل.',
      causesEn: 'Warm (27-30°C), humid (>90% RH), heavy dew; attacks stressed or mature plants. Nitrogen deficiency, heavy fruit load, drought stress, overhead irrigation.',
      causesAr: 'حرارة 27-30°م، رطوبة >90%، ندى كثيف، يهاجم النباتات المجهدة. نقص الآزوت، حمل ثمري ثقيل، إجهاد جفاف، ري علوي.',
      chemicalTreatmentEn: 'Chlorothalonil, mancozeb, or azoxystrobin on 7-14 day schedule; rotate FRAC codes.',
      chemicalTreatmentAr: 'كلوروثالونيل أو مانكوزيب أو أزوكسيستروبين كل 7-14 يوم، مع تبديل مجموعات الـ FRAC.',
      organicTreatmentEn: 'Copper sprays, Bacillus subtilis, remove lower leaves, mulch to prevent splash.',
      organicTreatmentAr: 'رش النحاس، Bacillus subtilis، إزالة الأوراق السفلى، تغطية التربة لمنع التناثر.',
      preventionEn: 'Stake and prune lower leaves; mulch; 2-year rotation; balanced fertilization; resistant varieties (Mountain Magic, Iron Lady).',
      preventionAr: 'تعريش وإزالة الأوراق السفلى، تغطية التربة، دورة زراعية سنتين، تسميد متوازن، أصناف مقاومة (Mountain Magic, Iron Lady).',
      severity: 'High', seasonEn: 'Mid to late summer', seasonAr: 'منتصف إلى أواخر الصيف',
      sourceUrl: 'https://extension.umn.edu/disease-management/early-blight-tomato-and-potato',
    ),
    'Tomato___Late_blight': DiseaseInfo(
      cropEn: 'Tomato', cropAr: 'طماطم',
      diseaseEn: 'Late Blight', diseaseAr: 'اللفحة المتأخرة',
      isHealthy: false,
      pathogenEn: 'Oomycete: Phytophthora infestans', pathogenAr: 'عضو الأومِسيتات: Phytophthora infestans',
      symptomsEn: 'Large water-soaked dark lesions on leaves and stems; white downy sporulation on undersides; firm brown greasy-looking patches on fruit; can kill whole plant in days.',
      symptomsAr: 'بقع كبيرة مشبعة بالماء داكنة على الأوراق والسيقان، زغب أبيض من الأسفل، بقع بنية صلبة ذات مظهر دهني على الثمار، يمكن أن يقتل النبات خلال أيام.',
      causesEn: 'Cool (15-20°C), wet, humid, foggy weather; rapid spread by wind-borne sporangia. Proximity to infected potatoes, tomato cull piles.',
      causesAr: 'طقس بارد (15-20°م) رطب ضبابي، الانتشار سريع عبر الأبواغ المحمولة بالرياح. قرب بطاطس مصابة، أكوام طماطم مستبعدة.',
      chemicalTreatmentEn: 'Protectant (mancozeb, chlorothalonil) + systemic (mandipropamid, cymoxanil) every 5-7 days under high pressure.',
      chemicalTreatmentAr: 'وقائي (مانكوزيب، كلوروثالونيل) + جهازي (mandipropamid, cymoxanil) كل 5-7 أيام تحت الضغط العالي.',
      organicTreatmentEn: 'Copper hydroxide preventively every 5 days; destroy infected plants immediately; no organic cure.',
      organicTreatmentAr: 'هيدروكسيد النحاس وقائيًا كل 5 أيام، إتلاف النباتات المصابة فورًا، لا يوجد علاج عضوي شافي.',
      preventionEn: 'Certified clean transplants; resistant varieties (Mountain Magic, Defiant PhR); drip irrigation; monitor USABlight forecasts.',
      preventionAr: 'شتلات معتمدة نظيفة، أصناف مقاومة (Mountain Magic, Defiant PhR)، ري بالتنقيط، متابعة تنبؤات USABlight.',
      severity: 'High', seasonEn: 'Cool wet periods (spring/fall)', seasonAr: 'الفترات الباردة الرطبة (ربيع/خريف)',
      sourceUrl: 'https://www.vegetables.cornell.edu/pest-management/disease-factsheets/late-blight/',
    ),
    'Tomato___Leaf_Mold': DiseaseInfo(
      cropEn: 'Tomato', cropAr: 'طماطم',
      diseaseEn: 'Leaf Mold', diseaseAr: 'عفن الأوراق',
      isHealthy: false,
      pathogenEn: 'Fungus: Passalora fulva (syn. Fulvia fulva)', pathogenAr: 'فطر: Passalora fulva',
      symptomsEn: 'Pale green-yellow spots on upper leaf surface; olive-green to brown velvety mold on lower surface; leaves curl and drop; mostly in greenhouses/high tunnels.',
      symptomsAr: 'بقع خضراء-صفراء باهتة على السطح العلوي، عفن مخملي زيتوني إلى بني على السطح السفلي، الأوراق تلتفّ وتسقط، شائع في الصوبات.',
      causesEn: 'High humidity (>85%), moderate temperatures (22-24°C), poor ventilation, still air. Enclosed structures, overhead watering, dense planting.',
      causesAr: 'رطوبة عالية (>85%)، حرارة معتدلة (22-24°م)، ضعف التهوية، هواء راكد. الصوبات المغلقة، الري العلوي، الزراعة الكثيفة.',
      chemicalTreatmentEn: 'Chlorothalonil or mancozeb; rotate with strobilurins (azoxystrobin) if resistance is not yet present.',
      chemicalTreatmentAr: 'كلوروثالونيل أو مانكوزيب، مع تبديل مع ستروبيلورينات (أزوكسيستروبين) إذا لم تظهر المقاومة.',
      organicTreatmentEn: 'Copper sprays (Champ 30 WG); Zonix (rhamnolipid); proper ventilation and pruning.',
      organicTreatmentAr: 'رش النحاس (Champ 30 WG)، Zonix (rhamnolipid)، تهوية وتقليم مناسبين.',
      preventionEn: 'Ventilate greenhouses; prune lower leaves; space plants; drip irrigation; resistant varieties (Red Mountain, Primo Red).',
      preventionAr: 'تهوية الصوبات، تقليم الأوراق السفلى، مسافات زراعة، ري بالتنقيط، أصناف مقاومة (Red Mountain, Primo Red).',
      severity: 'Medium', seasonEn: 'Greenhouse seasons; cool wet periods', seasonAr: 'مواسم الصوبات، الفترات الباردة الرطبة',
      sourceUrl: 'https://extension.umn.edu/disease-management/tomato-leaf-mold',
    ),
    'Tomato___Septoria_leaf_spot': DiseaseInfo(
      cropEn: 'Tomato', cropAr: 'طماطم',
      diseaseEn: 'Septoria Leaf Spot', diseaseAr: 'بقعة سبتوريا الورقية',
      isHealthy: false,
      pathogenEn: 'Fungus: Septoria lycopersici', pathogenAr: 'فطر: Septoria lycopersici',
      symptomsEn: 'Many small (~1/4 inch) circular spots with dark borders and pale gray/tan centers; black pycnidia visible in centers; starts on lower leaves; severe defoliation.',
      symptomsAr: 'بقع دائرية صغيرة كثيرة (~6 مم) بحواف داكنة ومراكز رمادية/فاتحة، نقاط سوداء (pycnidia) مرئية في المراكز، تبدأ من الأوراق السفلى، تسبب تساقط شديد للأوراق.',
      causesEn: 'Warm (15-27°C), humid (>90% RH), wet conditions; spreads as canopy closes. Dense canopy, water splash from soil, infected weeds (nightshade family).',
      causesAr: 'طقس دافئ (15-27°م)، رطب (>90%)، ينتشر عند انغلاق المجموع الخضري. مجموع خضري كثيف، تناثر الماء من التربة، أعشاب مصابة (فصيلة الباذنجان).',
      chemicalTreatmentEn: 'Chlorothalonil, mancozeb, or copper-based fungicides weekly starting early, before severe symptoms.',
      chemicalTreatmentAr: 'كلوروثالونيل أو مانكوزيب أو مبيدات نحاسية أسبوعيًا بدءًا مبكرًا قبل ظهور أعراض شديدة.',
      organicTreatmentEn: 'Copper + Bacillus subtilis; remove infected lower leaves; mulch heavily.',
      organicTreatmentAr: 'النحاس + Bacillus subtilis، إزالة الأوراق السفلى المصابة، تغطية التربة بطبقة سميكة.',
      preventionEn: 'Mulch, stake plants, 2-year rotation, weed control (nightshades), avoid overhead watering, resistant varieties.',
      preventionAr: 'تغطية التربة، تعريش، دورة زراعية سنتين، مكافحة الحشائش (الباذنجانيات)، تجنب الري العلوي، أصناف مقاومة.',
      severity: 'High', seasonEn: 'Mid summer onward', seasonAr: 'من منتصف الصيف',
      sourceUrl: 'https://extension.umn.edu/plant-diseases/tomato-leaf-spot-diseases',
    ),
    'Tomato___Spider_mites Two-spotted_spider_mite': DiseaseInfo(
      cropEn: 'Tomato', cropAr: 'طماطم',
      diseaseEn: 'Two-Spotted Spider Mite', diseaseAr: 'العنكبوت الأحمر ذو البقعتين',
      isHealthy: false,
      pathogenEn: 'Pest (mite): Tetranychus urticae', pathogenAr: 'آفة (عنكبوت): Tetranychus urticae',
      symptomsEn: 'Tiny white/yellow stippling on leaves; leaves bronze/bleach and drop; fine webbing on undersides in heavy infestations; "gold fleck" on fruit.',
      symptomsAr: 'نقط بيضاء/صفراء دقيقة على الأوراق، الأوراق تبرنزت/تبيضّ وتسقط، نسيج عنكبوتي دقيق تحت الأوراق في الإصابة الشديدة، نقط ذهبية على الثمار.',
      causesEn: 'Hot (>27°C), dry, dusty conditions; drought-stressed plants. Drought stress, dusty conditions, broad-spectrum insecticide use killing natural predators.',
      causesAr: 'ظروف حارة (>27°م) جافة مغبرة، نباتات مجهدة بالجفاف. إجهاد الجفاف، الظروف المغبرة، استخدام مبيدات واسعة الطيف تقتل الأعداء الطبيعية.',
      chemicalTreatmentEn: 'Miticides (bifenazate, abamectin, spiromesifen, etoxazole) rotated; use ONLY when needed.',
      chemicalTreatmentAr: 'مبيدات العناكب (bifenazate, abamectin, spiromesifen, etoxazole) مع التبديل، تُستخدم عند الحاجة فقط.',
      organicTreatmentEn: 'Water jet (strong spray), insecticidal soap, neem oil, horticultural oils; release Phytoseiulus persimilis (predatory mite).',
      organicTreatmentAr: 'رش ماء قوي، صابون حشري، زيت النيم، زيوت بستانية، إطلاق Phytoseiulus persimilis (عنكبوت مفترس).',
      preventionEn: 'Keep plants well-watered; wet pathways to reduce dust; avoid broad-spectrum insecticides; early monitoring with hand lens.',
      preventionAr: 'الحفاظ على الري الجيد، ترطيب الممرات لتقليل الغبار، تجنب المبيدات واسعة الطيف، المراقبة المبكرة بعدسة يدوية.',
      severity: 'Medium', seasonEn: 'Hot dry summer', seasonAr: 'الصيف الحار الجاف',
      sourceUrl: 'https://extension.umn.edu/yard-and-garden-insects/spider-mites',
    ),
    'Tomato___Target_Spot': DiseaseInfo(
      cropEn: 'Tomato', cropAr: 'طماطم',
      diseaseEn: 'Target Spot', diseaseAr: 'البقعة الهدفية',
      isHealthy: false,
      pathogenEn: 'Fungus: Corynespora cassiicola', pathogenAr: 'فطر: Corynespora cassiicola',
      symptomsEn: 'Small brown spots on leaves with light centers; can show concentric rings; fruit has small dark sunken spots that enlarge and crack open as fruit ripens.',
      symptomsAr: 'بقع بنية صغيرة على الأوراق بمركز فاتح، قد تظهر بحلقات دائرية، بقع داكنة غائرة صغيرة على الثمار تتسع وتتشقق أثناء النضج.',
      causesEn: 'Warm (20-30°C) humid weather; heavy dew; extended wet periods. Dense plantings, overhead irrigation, continuous tomato cropping.',
      causesAr: 'طقس دافئ (20-30°م) رطب، ندى كثيف، فترات رطبة طويلة. زراعة كثيفة، ري علوي، زراعة طماطم متواصلة.',
      chemicalTreatmentEn: 'Chlorothalonil, mancozeb, or strobilurins (pyraclostrobin, azoxystrobin); rotate FRAC groups.',
      chemicalTreatmentAr: 'كلوروثالونيل أو مانكوزيب أو ستروبيلورينات (pyraclostrobin, azoxystrobin)، مع تبديل مجموعات الـ FRAC.',
      organicTreatmentEn: 'Copper sprays; Bacillus subtilis; remove infected leaves; destroy debris.',
      organicTreatmentAr: 'رش النحاس، Bacillus subtilis، إزالة الأوراق المصابة، إتلاف البقايا.',
      preventionEn: 'Crop rotation, drip irrigation, airflow management, plant spacing, resistant cultivars where available.',
      preventionAr: 'دورة زراعية، ري بالتنقيط، إدارة التهوية، مسافات زراعة، أصناف مقاومة حيث تتوفر.',
      severity: 'Medium', seasonEn: 'Warm wet periods', seasonAr: 'الفترات الدافئة الرطبة',
      sourceUrl: 'https://ipm.ifas.ufl.edu/pdfs/Target_Spot.pdf',
    ),
    'Tomato___Tomato_Yellow_Leaf_Curl_Virus': DiseaseInfo(
      cropEn: 'Tomato', cropAr: 'طماطم',
      diseaseEn: 'Tomato Yellow Leaf Curl Virus (TYLCV)', diseaseAr: 'فيروس تجعد واصفرار أوراق الطماطم',
      isHealthy: false,
      pathogenEn: 'Virus: TYLCV (Begomovirus); vectored by silverleaf whitefly Bemisia tabaci',
      pathogenAr: 'فيروس: TYLCV (بيجوموفيروس)، تنقله الذبابة البيضاء Bemisia tabaci',
      symptomsEn: 'Severe stunting; small upward-curled leaves with yellow margins; shortened internodes; flower drop; few or no fruit if infected young.',
      symptomsAr: 'تقزم شديد، أوراق صغيرة ملتفة للأعلى بحواف صفراء، سلاميات قصيرة، تساقط الأزهار، إنتاج ضعيف أو معدوم إذا أُصيب النبات صغيرًا.',
      causesEn: 'Hot, dry regions favor whitefly reproduction. Proximity to infected tomato or weed hosts; heavy whitefly pressure.',
      causesAr: 'المناطق الحارة الجافة تساعد تكاثر الذبابة البيضاء. قرب نباتات طماطم أو أعشاب مصابة، ضغط عالٍ من الذبابة البيضاء.',
      chemicalTreatmentEn: 'No cure. Control whiteflies with imidacloprid, dinotefuran, spirotetramat; rotate chemistries to prevent resistance.',
      chemicalTreatmentAr: 'لا يوجد علاج. مكافحة الذبابة البيضاء بـ imidacloprid, dinotefuran, spirotetramat مع التبديل لمنع المقاومة.',
      organicTreatmentEn: 'Neem/azadirachtin, insecticidal soap, pyrethrin; metalized/silver reflective mulch to repel whiteflies; yellow sticky traps.',
      organicTreatmentAr: 'نيم/أزاديراكتين، صابون حشري، بيرثرين، تغطية فضية/معدنية لطرد الذبابة البيضاء، مصائد صفراء لاصقة.',
      preventionEn: 'Resistant varieties (Ty-1/Ty-3 genes); tomato-free period (2 months); remove infected plants in sealed bags; reflective mulch.',
      preventionAr: 'أصناف مقاومة (جينات Ty-1/Ty-3)، فترة خالية من الطماطم (شهرين)، إزالة النباتات المصابة في أكياس محكمة، تغطية عاكسة.',
      severity: 'High', seasonEn: 'Year-round in warm climates', seasonAr: 'طوال العام في المناخات الدافئة',
      sourceUrl: 'https://ipm.ifas.ufl.edu/agricultural_ipm/tylcv_home_mgmt.shtml',
    ),
    'Tomato___Tomato_mosaic_virus': DiseaseInfo(
      cropEn: 'Tomato', cropAr: 'طماطم',
      diseaseEn: 'Tomato Mosaic Virus (ToMV)', diseaseAr: 'فيروس موزاييك الطماطم',
      isHealthy: false,
      pathogenEn: 'Virus: Tomato Mosaic Virus (Tobamovirus)', pathogenAr: 'فيروس: Tomato Mosaic Virus (توباموفيروس)',
      symptomsEn: 'Mottled light and dark green leaves; curled, malformed, small leaves; stunted plants if infected early; uneven fruit ripening; internal fruit browning.',
      symptomsAr: 'تبقع فاتح وداكن من اللون الأخضر على الأوراق، أوراق ملتفة مشوهة صغيرة، تقزم إذا أُصيب مبكرًا، نضج غير منتظم للثمار، اسمرار داخلي للثمار.',
      causesEn: 'Spread mechanically via tools, hands, tobacco products, contaminated seeds; very stable virus persisting in debris for years.',
      causesAr: 'ينتقل ميكانيكيًا عبر الأدوات والأيدي ومنتجات التبغ والبذور الملوثة، فيروس ثابت جدًا يبقى في البقايا لسنوات.',
      chemicalTreatmentEn: 'No chemical cure for plant viruses; focus on prevention and vector control.',
      chemicalTreatmentAr: 'لا يوجد علاج كيميائي للفيروسات النباتية، ركّز على الوقاية ومكافحة الناقلات.',
      organicTreatmentEn: 'No organic cure; remove infected plants; disinfect tools with 10% bleach or trisodium phosphate.',
      organicTreatmentAr: 'لا يوجد علاج عضوي، إزالة النباتات المصابة، تعقيم الأدوات بكلور 10% أو فوسفات ثلاثي الصوديوم.',
      preventionEn: 'Resistant varieties (ToMV/Tm-2 gene); certified seed; hot-water seed treatment (50°C, 25 min); no tobacco near plants; wash hands/tools.',
      preventionAr: 'أصناف مقاومة (جين ToMV/Tm-2)، بذور معتمدة، معالجة بالماء الساخن (50°م، 25 دقيقة)، منع التبغ قرب النباتات، غسل اليدين والأدوات.',
      severity: 'High', seasonEn: 'All seasons (persistent in debris)', seasonAr: 'جميع المواسم (يبقى في البقايا)',
      sourceUrl: 'https://extension.umn.edu/disease-management/tomato-viruses',
    ),
    'Tomato___healthy': DiseaseInfo(
      cropEn: 'Tomato', cropAr: 'طماطم',
      diseaseEn: 'Healthy', diseaseAr: 'سليم', isHealthy: true,
      pathogenEn: 'None', pathogenAr: 'لا يوجد',
      symptomsEn: _hSymptomsEn, symptomsAr: _hSymptomsAr,
      causesEn: _hCausesEn, causesAr: _hCausesAr,
      chemicalTreatmentEn: _hChemEn, chemicalTreatmentAr: _hChemAr,
      organicTreatmentEn: _hOrgEn, organicTreatmentAr: _hOrgAr,
      preventionEn: _hPrevEn, preventionAr: _hPrevAr,
      severity: 'None', seasonEn: 'All seasons', seasonAr: 'جميع المواسم',
      sourceUrl: 'https://www.apsnet.org/edcenter/Pages/default.aspx',
    ),
  };

  static DiseaseInfo resolve(String label) {
    return _db[label] ??
        DiseaseInfo(
          cropEn: 'Unknown', cropAr: 'غير معروف',
          diseaseEn: label, diseaseAr: label,
          isHealthy: label.toLowerCase().contains('healthy'),
          pathogenEn: 'Unknown', pathogenAr: 'غير معروف',
          symptomsEn: 'No information available for this class.',
          symptomsAr: 'لا توجد معلومات متاحة لهذا الصنف.',
          causesEn: 'No information available.',
          causesAr: 'لا توجد معلومات متاحة.',
          chemicalTreatmentEn: 'Consult a local agronomist.',
          chemicalTreatmentAr: 'استشر مهندسًا زراعيًا محليًا.',
          organicTreatmentEn: 'Consult a local agronomist.',
          organicTreatmentAr: 'استشر مهندسًا زراعيًا محليًا.',
          preventionEn: 'Follow general good agricultural practices.',
          preventionAr: 'اتبع الممارسات الزراعية الجيدة العامة.',
          severity: 'Unknown', seasonEn: 'Unknown', seasonAr: 'غير معروف',
          sourceUrl: '',
        );
  }
}
